concurrency:
  group: cicd
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rust-src
          target: x86_64-unknown-linux-musl, i686-pc-windows-gnu, x86_64-pc-windows-gnu, wasm32-unknown-unknown
      - run: cargo install mdbook
      - run: cargo install trunk
      - run: sudo apt install -y mingw-w64 build-essential
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          name: release.tar.gz
          path: covert_c2_ping.tar.gz
      - uses: actions/upload-pages-artifact@v1
        with:
          path: out/doc

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1