concurrency:
  group: cicd
  cancel-in-progress: true

on:
  push:
    branches: ["main"]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      - run: source $HOME/.cargo/env
      - run: rustup default nightly
      - run: rustup update
      - run: rustup target add wasm32-unknown-unknown
      - run: rustup target add x86_64-unknown-linux-musl
      - run: rustup target add x86_64-pc-windows-gnu
      - run: rustup target add i686-pc-windows-gnu
      - run: rustup component add rust-src
      - run: cargo install mdbook
      - run: cargo install trunk
      - run: cargo install cross
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          name: release.tar.gz
          path: covert_c2_ping.tar.gz
      - uses: actions/upload-pages-artifact@v1
        with:
          path: out/doc

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
